#Default Configuration File - Developed by mkafrin
Teamspeak: No Teamspeak currently setup
Mumble: No Mumble currently setup
Ventrilo: No Ventrilo currently setup
Website: No link to website
Donation page: No link to donation page
Forums: No link to forums
FAQ: No link to FAQ
Extra Info: No extra info yet